name: NodeJs

on:
  push:
    branches:
      - master

permissions:
  security-events: write
  issues: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]
        exclude:
          - os: windows-latest
            node-version: 22

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: npm install

      - name: Test
        run: npm test

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: |
            package*

      - name: Deploy
        run: echo "code is deployed"
